Sprint 1/step 2
AlexKorostelev/react-burger pull request #2
Opened 2023-01-08 21:50 UTC by AlexKorostelev

Исправлено:
1. Вывод всего списка ингредиентов (ранее - выводилось согласно выбранной в табе категории)
2. Первый и последний элементы в конструкторе отображаются согласно дизайн-макету
3. Используемые в 2-х компонентах PropTypes вынесены в отдельный файл.

2023-01-09 09:36 UTC, andryxxa93 requested changes
Все замечания из предыдущей проверки были исправлены - это здорово!
Но для финального этапа сдачи работы требуется:
- Удалить моковые данные и получать данные с сервера.
- Добавить модальное окно для открытия данных заказа и данных ингредиента.

Пожалуйста просмотрите ещё раз требования к текущему этапу сдачи работы.
Удачи!

2023-01-09 09:36 UTC, andryxxa93 commented on src/utils/types.js
> +export const mockedDataPropTypes = {
**Можно лучше**
Не совсем корректно называть типизацию ингредиента `mockedDataPropTypes` потому что на данном этапе вы должны использовать не моковые данные, а данные получаемые с сервера.

2023-01-14 10:52 UTC, AlexKorostelev commented
> 

Добавлено модальное окно для показа ингредиента, оформления заказа.

2023-01-14 15:41 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- Измените логику ModalOverlay - у него не должно быть `children`.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-14 15:41 UTC, andryxxa93 commented on src/components/App/App.jsx
> +        const res = await fetch(`${baseApiUrl}/ingredients`);
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-01-14 15:41 UTC, andryxxa93 commented on src/components/App/App.jsx
> +    const getProductData = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-01-14 15:41 UTC, andryxxa93 commented on src/components/App/App.jsx
> +        </Modal>)}
**МОжно лучше**
Лучше использовать модалку внутри компонентов к которым она относится - `BurgerIngredients` и `BurgerConstructor`

2023-01-14 15:41 UTC, andryxxa93 commented on src/components/AppHeader/NavButton/NavButton.jsx
> +	url: PropTypes.string
**Можно лучше**
Похоже лишний prop затесался

2023-01-14 15:41 UTC, andryxxa93 commented on src/components/Modal/Modal.jsx
> +      window.removeEventListener('keydown', onClose);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-01-14 15:41 UTC, andryxxa93 commented on src/components/Modal/ModalOverlay/ModalOverlay.jsx
> +            {children}
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2023-01-15 13:16 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-15 20:59 UTC, merged