Sprint 2/step 2
AlexKorostelev/react-burger pull request #4
Opened 2023-01-27 20:13 UTC by AlexKorostelev

Выполнение второй части спринта согласно чеклисту.

2023-01-27 21:57 UTC, andryxxa93 requested changes
Отличная работа! `Redux` и `DnD` настроены и работают верно.
Что понравилось:
- Реализован скролл по категориям
- Для запросов api созданы необходимые усилители
- Редьюсеры и экшены разделены по файлам в зависимости от задачи которую они решают

Есть одно замечание, которое необходимо исправить, чтобы работа была принята:
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.


Удачи!

2023-01-27 21:57 UTC, andryxxa93 commented on src/components/App/App.jsx
> +  const { ingredients, ingredientsFailed } = useSelector(store => store.ingredients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-01-27 21:57 UTC, andryxxa93 commented on src/components/BurgerIngredients/IngredientGroup/IngredientGroup.jsx
> +    const ingredientsGroup = ingredients.filter(item => item.type === groupName);
**Можно лучше**
Тут можно использовать `useMemo`

2023-01-27 21:57 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const totalPrice = constructorItems.reduce((acc, item) => acc + item.price, 0);
**Можно лучше**
Такую операцию лучше поместить в `useMemo`, иначе она будет выполняться каждый рендер

2023-01-28 09:18 UTC, AlexKorostelev commented on src/components/App/App.jsx
> +  const { ingredients, ingredientsFailed } = useSelector(store => store.ingredients);
Андрей, привет! Не совсем понял что ты имеешь ввиду - нужно передавать второй параметр в useSelector (функцию глубокого сравнения) для избежания повторного вызова useSelector?

2023-01-28 09:44 UTC, andryxxa93 commented on src/components/App/App.jsx
> +  const { ingredients, ingredientsFailed } = useSelector(store => store.ingredients);
Привет! Смотри, сейчас ты передаешь внутрь `useSelector` функцию - `store => store.ingredients`. Это анонимная функция - она создается каждый рендер, а функция относится к ссылочному типу данных. Т.е. она сравнивается не по значению, а по ссылке. Получается, что каждый рендер у нас новая ссылка будет, хотя функция по смыслу та же. `useSelector` может не понять этого и сработать лишний раз. Удобнее будет если создать именованную функцию селектор. 
`expoty const selectIngredients = store => store.ingredients`
и передавать её в `useSelector` => `useSelector(selectIngredients)`;

2023-01-28 09:46 UTC, andryxxa93 approved these changes
Супер! Работа принята, удачного продолжения обучения!

2023-01-28 22:16 UTC, merged